name: menu_tres_tipos_flutter
description: Proyecto Flutter con Drawer, Dropdown y Popup Menu en una misma interfaz.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
